In [2]:
import pandas as pd
import numpy as np
import os

In [5]:
df = pd.read_csv("/content/building_energy_800k.csv")

In [7]:
df.head()

,timestamp,electricity,chilled_water,steam,hot_water,gas,water,temperature,humidity
0,2016-01-01 00:00:00,63.394,48.528,21.342,18.743,14.282,6.803,12.56,36.76
1,2016-01-01 01:00:00,47.025,32.197,17.469,18.358,12.309,6.189,23.68,85.43
2,2016-01-01 02:00:00,55.048,41.767,27.018,15.952,13.382,8.331,24.75,37.80
3,2016-01-01 03:00:00,56.905,40.457,27.242,12.251,12.037,7.641,-9.13,100.00
4,2016-01-01 04:00:00,43.597,47.617,21.106,20.305,11.327,6.907,13.36,65.29

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244558 entries, 0 to 244557
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   timestamp      244558 non-null  object
 1   electricity    244558 non-null  float64
 2   chilled_water  244557 non-null  float64
 3   steam          244557 non-null  float64
 4   hot_water      244557 non-null  float64
 5   gas            244557 non-null  float64
 6   water          244557 non-null  float64
 7   temperature    244557 non-null  float64
 8   humidity       244557 non-null  float64
dtypes: float64(8), object(1)
memory usage: 16.8+ MB

In [9]:
import pandas as pd
import os

def load_data(file_path):

    print("Loading Data...")

    # Check if file exists
    if not os.path.exists(file_path):
        raise FileNotFoundError("File not found. Please check the path.")

    # Read CSV
    df = pd.read_csv(file_path)

    print("Raw Shape:", df.shape)

    return df


# 🔽🔽 PUT YOUR FULL CSV PATH HERE 🔽🔽
csv_path = "/content/building_energy_800k.csv"

df = load_data(csv_path)

df.head()

Loading Data...
Raw Shape: (244558, 9)

,timestamp,electricity,chilled_water,steam,hot_water,gas,water,temperature,humidity
0,2016-01-01 00:00:00,63.394,48.528,21.342,18.743,14.282,6.803,12.56,36.76
1,2016-01-01 01:00:00,47.025,32.197,17.469,18.358,12.309,6.189,23.68,85.43
2,2016-01-01 02:00:00,55.048,41.767,27.018,15.952,13.382,8.331,24.75,37.80
3,2016-01-01 03:00:00,56.905,40.457,27.242,12.251,12.037,7.641,-9.13,100.00
4,2016-01-01 04:00:00,43.597,47.617,21.106,20.305,11.327,6.907,13.36,65.29